targets:
  $default:
    builders:
      built_stream_generator|built_stream:
        generate_for:
          - lib/streams/built_single_stream/**.dart
          - lib/streams/built_composed_streams/**.dart