name: example
description: A project used to demo 
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # built_stream: ^1.0.4

dev_dependencies:
  analyzer: ">=0.34.0 <=0.40.0"
  build_runner: 1.7.2
  flutter_test:
    sdk: flutter
  customized_streams: 1.0.16
  rxdart: ^0.24.1
  # built_stream_generator: ^1.0.9


dependency_overrides:
  built_stream:
    path: ../built_stream
  built_stream_generator:
    path: ../built_stream_generator
