name: built_stream
description: This library is the runtime dependency.
version: 1.0.5
homepage: https://github.com/datvt9312/flutter_bloc/built_stream

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  test: ^1.15.3
