targets:
  $default:
    builders:
      built_stream_generator|built_stream:
        enabled: true

builders:
  built_stream:
    target: ":built_stream_generator"
    import: "package:built_stream_generator/builder.dart"
    builder_factories: ["builtStream"]
    build_extensions: {".dart": [".built_stream.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]