name: built_stream_generator
description: This library is the dev dependency.
version: 1.0.11
homepage: https://github.com/datvt9312/flutter_bloc/built_stream_generator

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  analyzer: ">=0.34.0 <0.39.0"
  build: ^1.0.0
  built_collection: ">=2.0.0 <5.0.0"
  source_gen: ^0.9.0
  # built_stream: "^1.0.4"

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  built_stream:
    path: ../built_stream
