name: built_stream_generator
description: >
  Provide built stream for Dart
  This library is the dev dependency.
version: 1.0.28
homepage: https://github.com/vo9312/built_stream.dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  analyzer: ">=0.34.0 <=0.40.0"
  build: ^1.0.0
  built_collection: ">=2.0.0 <5.0.0"
  source_gen: ^0.9.0
  built_stream: ^1.0.7
  meta: ^1.1.8
  customized_streams: ^1.0.16
dev_dependencies:
  test: ^1.0.0

# dependency_overrides:
#   built_stream:
#     path: ../built_stream
